---
name: Pull Request Pipeline

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - dev
  #     - prod
  pull_request:
    branches:
      - dev
      - prod

permissions:
  id-token: write
  contents: read

jobs:
  deploy-environments:
    name: Deploy environments
    runs-on: ubuntu-latest
    env:
      TENANT_ID: 380adf45-465e-486c-92c1-a3a9e4f6c62d
      SUBSCRIPTION_ID: 3e1e6407-7334-4898-bb27-b68e97a6b32e # ME-MngEnvMCAP402121-playground
      # https://portal.azure.com/?feature.msaljs=true#view/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/~/Overview/appId/f2e9146b-f46e-4ddd-9367-4e4b9fa06fa9/isMSAApp~/false
      # AppReg that has Owner permissions on the subscription
      CLIENT_ID: f2e9146b-f46e-4ddd-9367-4e4b9fa06fa9
      ENVIRONMENT: ${{ github.ref == 'refs/heads/prod' && 'PROD' || 'DEV' }}
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          enable-AzPSSession: true
          # AppReg client secret: https://github.com/EmeaAppGbb/multitenancy-infra/settings/secrets/actions
          creds: >
            {
            "clientId":"${{ env.CLIENT_ID }}",
            "clientSecret":"${{ secrets.AZURE_SP_SECRET }}",
            "subscriptionId":"${{ env.SUBSCRIPTION_ID }}",
            "tenantId":"${{ env.TENANT_ID }}"
            }

      - name: Reconciliate Bicep template
        id: reconciliate
        uses: azure/arm-deploy@v2
        with:
          scope: subscription
          subscriptionId: ${{ env.SUBSCRIPTION_ID }}
          template: infra/main.bicep
          region: westeurope
          parameters: >
            infra/main.${{ env.ENVIRONMENT }}.bicepparam
          additionalArguments: "--what-if"

      - uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        env:
          PLAN: "biceps\n${{ steps.reconciliate.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            <details><summary>Validation Output</summary>

            </details>

            #### Biceps Reconciliation Plan 📖\`${{ steps.reconciliate.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \, Workflow: \`${{ github.workflow }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })